#! /bin/bash

set -e

cd ../reg-backend-template-test
go-generator-cli --create --generator=../reg-backend-template --target=.
go-generator-cli --render --generator=../reg-backend-template --target=.
go fmt ./...
go build ./...
go test ./...
go vet ./...
echo "success, now check differences"
